if(NOT EXISTS ${dst})
  execute_process(COMMAND ${CMAKE_COMMAND} -E make_directory ${dst})
endif()
separate_arguments(src)
foreach(item ${src})
  if(IS_ABSOLUTE ${item})
    set(fp ${item})
  else()
    set(fp ${srcDir}/${item})
  endif()
  get_filename_component(itemDir ${fp} PATH)
  if(EXISTS ${itemDir})
    file(GLOB files ${fp})
    foreach(f ${files})
      if(UNIX)
        file(RELATIVE_PATH rp ${dst} ${f})
        get_filename_component(fn ${f} NAME)
        execute_process(COMMAND ${CMAKE_COMMAND} -E create_symlink ${rp} ${fn}
          WORKING_DIRECTORY ${dst}
          )
      else()
        execute_process(COMMAND ${CMAKE_COMMAND} -E copy_if_different ${f} ${dst})
      endif()
    endforeach()
  endif()
endforeach()
