#ifndef MK1MF_BUILD
  /* auto-generated by crypto/CMakeLists.txt for crypto/cversion.c */
  #define CFLAGS "@CMAKE_C_COMPILER@ @CMAKE_C_FLAGS@"
  #define PLATFORM "@CMAKE_SYSTEM_NAME@"
  #define DATE "@BUILDINF_DATE@"
#endif
